-- MySQL Script generated by MySQL Workbench
-- Tue 22 Oct 2019 04:55:15 PM CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema shop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema shop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shop` DEFAULT CHARACTER SET utf8 ;
USE `shop` ;

-- -----------------------------------------------------
-- Table `shop`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`users` (
  `email` NVARCHAR(255) NOT NULL,
  `password` VARCHAR(45) NULL,
  `firstName` NVARCHAR(30) NULL,
  `lastName` NVARCHAR(30) NULL,
  `address` VARCHAR(255) NULL,
  `phone` VARCHAR(15) NULL,
  `type` ENUM('BUYER', 'SELLER', 'ADMIN') NULL DEFAULT 'BUYER',
  PRIMARY KEY (`email`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `category` VARCHAR(45) NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `description` TEXT NULL,
  `quantity` INT NULL DEFAULT 0,
  `image` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idProduct_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`product_lists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`product_lists` (
  `user` NVARCHAR(255) NULL,
  `listId` INT NOT NULL,
  `isShoppingCart` TINYINT(1) NULL,
  PRIMARY KEY (`listId`),
  UNIQUE INDEX `cartId_UNIQUE` (`listId` ASC),
  CONSTRAINT `fk_email`
    FOREIGN KEY (`user`)
    REFERENCES `shop`.`users` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`lists_to_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`lists_to_products` (
  `listId` INT NOT NULL,
  `productId` INT NOT NULL,
  PRIMARY KEY (`listId`, `productId`),
  INDEX `fk_list_to_product_1_idx` (`productId` ASC),
  CONSTRAINT `product`
    FOREIGN KEY (`productId`)
    REFERENCES `shop`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `list`
    FOREIGN KEY (`listId`)
    REFERENCES `shop`.`product_lists` (`listId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
